In [1]:
import pandas as pd
import requests

In [2]:
class ScriptData:
    def __init__(self, api_key):
        self.api_key = api_key

    def fetch_intraday_data(self, script):
        url = f"https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol={script}&interval=5min&apikey={self.api_key}"
        response = requests.get(url)
        data = response.json()
        self.data = data['Time Series (5min)']

    def convert_intraday_data(self, script):
        timestamps = []
        signals = []

        for timestamp, values in self.data.items():
            timestamps.append(pd.Timestamp(timestamp))
            signal = values['signal']  # Assuming the signal is included in the values
            signals.append(signal)

        df = pd.DataFrame({
            'timestamp': timestamps,
            'signal': signals
        })

        return df

In [3]:
api_key = 'CRNISN6GVDB0I2NZ'  # Replace with your actual API key
script_data = ScriptData(api_key)

In [4]:
script_data.fetch_intraday_data('NVDA')

In [5]:
print(script_data.data)

{'2023-06-16 19:55:00': {'1. open': '427.7000', '2. high': '427.7500', '3. low': '427.6000', '4. close': '427.6200', '5. volume': '9161'}, '2023-06-16 19:50:00': {'1. open': '427.7900', '2. high': '427.9400', '3. low': '427.6000', '4. close': '427.6000', '5. volume': '9061'}, '2023-06-16 19:45:00': {'1. open': '427.3700', '2. high': '427.7200', '3. low': '427.3300', '4. close': '427.7200', '5. volume': '7317'}, '2023-06-16 19:40:00': {'1. open': '427.5399', '2. high': '427.5399', '3. low': '427.3500', '4. close': '427.3500', '5. volume': '3395'}, '2023-06-16 19:35:00': {'1. open': '427.4500', '2. high': '427.5499', '3. low': '427.4000', '4. close': '427.4300', '5. volume': '2121'}, '2023-06-16 19:30:00': {'1. open': '427.4200', '2. high': '427.5000', '3. low': '427.4000', '4. close': '427.4500', '5. volume': '4834'}, '2023-06-16 19:25:00': {'1. open': '427.5700', '2. high': '427.5900', '3. low': '427.5000', '4. close': '427.5000', '5. volume': '6176'}, '2023-06-16 19:20:00': {'1. open': '427.6500', '2. high': '427.6500', '3. low': '427.5700', '4. close': '427.5700', '5. volume': '3080'}, '2023-06-16 19:15:00': {'1. open': '427.7000', '2. high': '427.7000', '3. low': '427.7000', '4. close': '427.7000', '5. volume': '281'}, '2023-06-16 19:10:00': {'1. open': '427.5600', '2. high': '427.6100', '3. low': '427.5500', '4. close': '427.6100', '5. volume': '1370'}, '2023-06-16 19:05:00': {'1. open': '427.7000', '2. high': '427.7000', '3. low': '427.6500', '4. close': '427.6500', '5. volume': '437'}, '2023-06-16 19:00:00': {'1. open': '427.6600', '2. high': '427.6600', '3. low': '427.5600', '4. close': '427.6100', '5. volume': '915'}, '2023-06-16 18:55:00': {'1. open': '427.7500', '2. high': '427.7500', '3. low': '427.5600', '4. close': '427.5646', '5. volume': '1590'}, '2023-06-16 18:50:00': {'1. open': '427.6062', '2. high': '427.6900', '3. low': '427.5200', '4. close': '427.6900', '5. volume': '3226'}, '2023-06-16 18:45:00': {'1. open': '427.7000', '2. high': '427.7000', '3. low': '427.6500', '4. close': '427.6500', '5. volume': '2220'}, '2023-06-16 18:40:00': {'1. open': '427.7001', '2. high': '427.8000', '3. low': '427.7001', '4. close': '427.7400', '5. volume': '4981'}, '2023-06-16 18:35:00': {'1. open': '427.7700', '2. high': '427.7900', '3. low': '427.6801', '4. close': '427.7200', '5. volume': '6466'}, '2023-06-16 18:30:00': {'1. open': '427.6300', '2. high': '427.7900', '3. low': '427.6253', '4. close': '427.7900', '5. volume': '4089'}, '2023-06-16 18:25:00': {'1. open': '427.6100', '2. high': '427.7200', '3. low': '427.6100', '4. close': '427.6900', '5. volume': '6597'}, '2023-06-16 18:20:00': {'1. open': '427.6100', '2. high': '427.6400', '3. low': '427.6100', '4. close': '427.6100', '5. volume': '1455'}, '2023-06-16 18:15:00': {'1. open': '427.5500', '2. high': '427.6500', '3. low': '427.5000', '4. close': '427.6500', '5. volume': '1272'}, '2023-06-16 18:10:00': {'1. open': '427.7400', '2. high': '427.7400', '3. low': '427.6301', '4. close': '427.6500', '5. volume': '1964'}, '2023-06-16 18:05:00': {'1. open': '427.5000', '2. high': '427.6940', '3. low': '427.4500', '4. close': '427.6940', '5. volume': '4154'}, '2023-06-16 18:00:00': {'1. open': '427.5100', '2. high': '427.5500', '3. low': '427.4001', '4. close': '427.4100', '5. volume': '4348'}, '2023-06-16 17:55:00': {'1. open': '427.8400', '2. high': '427.8500', '3. low': '427.5300', '4. close': '427.5300', '5. volume': '8233'}, '2023-06-16 17:50:00': {'1. open': '427.7100', '2. high': '427.8400', '3. low': '427.7100', '4. close': '427.8400', '5. volume': '4119'}, '2023-06-16 17:45:00': {'1. open': '427.6100', '2. high': '427.7500', '3. low': '427.6100', '4. close': '427.7500', '5. volume': '1787'}, '2023-06-16 17:40:00': {'1. open': '427.6000', '2. high': '427.7000', '3. low': '427.5000', '4. close': '427.5000', '5. volume': '3554'}, '2023-06-16 17:35:00': {'1. open': '427.5163', '2. high': '427.6500', '3. low': '427.5163', '4. close': '427.6100', '5. volume': '3033'}, '2023-06-16 17:30:00': {'1. open': '427.5100', '2. high': '427.8800', '3. low': '427.5099', '4. close': '427.7000', '5. volume': '6436'}, '2023-06-16 17:25:00': {'1. open': '427.5000', '2. high': '427.5000', '3. low': '427.4000', '4. close': '427.5000', '5. volume': '3971'}, '2023-06-16 17:20:00': {'1. open': '427.4653', '2. high': '427.4653', '3. low': '427.3200', '4. close': '427.3700', '5. volume': '2598'}, '2023-06-16 17:15:00': {'1. open': '427.5200', '2. high': '427.6499', '3. low': '427.5000', '4. close': '427.5100', '5. volume': '6002'}, '2023-06-16 17:10:00': {'1. open': '427.3593', '2. high': '427.5700', '3. low': '427.3593', '4. close': '427.5100', '5. volume': '2939'}, '2023-06-16 17:05:00': {'1. open': '427.4148', '2. high': '427.5900', '3. low': '427.2999', '4. close': '427.5900', '5. volume': '10160'}, '2023-06-16 17:00:00': {'1. open': '427.3500', '2. high': '427.5800', '3. low': '427.3500', '4. close': '427.3900', '5. volume': '4035'}, '2023-06-16 16:55:00': {'1. open': '427.2505', '2. high': '427.6000', '3. low': '427.2500', '4. close': '427.4500', '5. volume': '2387'}, '2023-06-16 16:50:00': {'1. open': '427.4100', '2. high': '427.4100', '3. low': '427.2000', '4. close': '427.2700', '5. volume': '4987'}, '2023-06-16 16:45:00': {'1. open': '427.2000', '2. high': '427.5000', '3. low': '426.9200', '4. close': '427.4100', '5. volume': '102489'}, '2023-06-16 16:40:00': {'1. open': '427.6000', '2. high': '427.6000', '3. low': '426.9200', '4. close': '427.1200', '5. volume': '113815'}, '2023-06-16 16:35:00': {'1. open': '427.8000', '2. high': '427.9500', '3. low': '427.4501', '4. close': '427.4700', '5. volume': '15724'}, '2023-06-16 16:30:00': {'1. open': '427.6100', '2. high': '427.9000', '3. low': '426.9200', '4. close': '427.8000', '5. volume': '372718'}, '2023-06-16 16:25:00': {'1. open': '427.5400', '2. high': '427.8000', '3. low': '427.2600', '4. close': '427.7000', '5. volume': '15449'}, '2023-06-16 16:20:00': {'1. open': '427.0900', '2. high': '427.6000', '3. low': '426.9200', '4. close': '427.6000', '5. volume': '37148'}, '2023-06-16 16:15:00': {'1. open': '427.0500', '2. high': '427.1700', '3. low': '426.9200', '4. close': '427.0900', '5. volume': '164386'}, '2023-06-16 16:10:00': {'1. open': '427.2700', '2. high': '427.3000', '3. low': '426.9200', '4. close': '427.0500', '5. volume': '752549'}, '2023-06-16 16:05:00': {'1. open': '427.0700', '2. high': '427.2800', '3. low': '426.9000', '4. close': '427.2800', '5. volume': '846998'}, '2023-06-16 16:00:00': {'1. open': '426.9200', '2. high': '427.2500', '3. low': '426.4400', '4. close': '427.0000', '5. volume': '734545'}, '2023-06-16 15:55:00': {'1. open': '428.9000', '2. high': '428.9650', '3. low': '426.6050', '4. close': '427.0250', '5. volume': '2364554'}, '2023-06-16 15:50:00': {'1. open': '430.1500', '2. high': '430.1899', '3. low': '427.7201', '4. close': '428.9513', '5. volume': '1815973'}, '2023-06-16 15:45:00': {'1. open': '429.6500', '2. high': '430.7800', '3. low': '429.5400', '4. close': '430.1650', '5. volume': '674878'}, '2023-06-16 15:40:00': {'1. open': '429.9100', '2. high': '429.9500', '3. low': '429.4001', '4. close': '429.5969', '5. volume': '473203'}, '2023-06-16 15:35:00': {'1. open': '429.8700', '2. high': '430.3700', '3. low': '429.3600', '4. close': '429.8935', '5. volume': '455803'}, '2023-06-16 15:30:00': {'1. open': '429.7499', '2. high': '430.5599', '3. low': '429.4101', '4. close': '429.8226', '5. volume': '546630'}, '2023-06-16 15:25:00': {'1. open': '430.5483', '2. high': '430.6183', '3. low': '429.5500', '4. close': '429.7000', '5. volume': '432341'}, '2023-06-16 15:20:00': {'1. open': '430.5700', '2. high': '430.9800', '3. low': '430.1900', '4. close': '430.5444', '5. volume': '474999'}, '2023-06-16 15:15:00': {'1. open': '429.1500', '2. high': '430.7099', '3. low': '429.1101', '4. close': '430.5350', '5. volume': '648308'}, '2023-06-16 15:10:00': {'1. open': '430.5250', '2. high': '430.9600', '3. low': '429.1200', '4. close': '429.1329', '5. volume': '793092'}, '2023-06-16 15:05:00': {'1. open': '430.5700', '2. high': '430.9900', '3. low': '430.1101', '4. close': '430.5500', '5. volume': '534979'}, '2023-06-16 15:00:00': {'1. open': '431.1800', '2. high': '431.3948', '3. low': '430.0600', '4. close': '430.5700', '5. volume': '712364'}, '2023-06-16 14:55:00': {'1. open': '432.3142', '2. high': '432.6000', '3. low': '431.0700', '4. close': '431.1350', '5. volume': '404369'}, '2023-06-16 14:50:00': {'1. open': '432.1300', '2. high': '432.7100', '3. low': '431.9200', '4. close': '432.3181', '5. volume': '337953'}, '2023-06-16 14:45:00': {'1. open': '432.3961', '2. high': '432.7795', '3. low': '431.9500', '4. close': '432.1200', '5. volume': '295464'}, '2023-06-16 14:40:00': {'1. open': '432.8600', '2. high': '432.9091', '3. low': '431.9701', '4. close': '432.3865', '5. volume': '401581'}, '2023-06-16 14:35:00': {'1. open': '432.6271', '2. high': '433.2051', '3. low': '432.4800', '4. close': '432.8386', '5. volume': '291814'}, '2023-06-16 14:30:00': {'1. open': '433.5300', '2. high': '433.5651', '3. low': '432.3400', '4. close': '432.6000', '5. volume': '414560'}, '2023-06-16 14:25:00': {'1. open': '434.1355', '2. high': '434.1355', '3. low': '433.3200', '4. close': '433.5700', '5. volume': '308515'}, '2023-06-16 14:20:00': {'1. open': '434.1399', '2. high': '434.2000', '3. low': '433.2900', '4. close': '434.0600', '5. volume': '237398'}, '2023-06-16 14:15:00': {'1. open': '434.1479', '2. high': '434.5237', '3. low': '433.7600', '4. close': '434.1261', '5. volume': '265554'}, '2023-06-16 14:10:00': {'1. open': '433.5900', '2. high': '434.4400', '3. low': '433.5400', '4. close': '434.1900', '5. volume': '310755'}, '2023-06-16 14:05:00': {'1. open': '433.0200', '2. high': '433.8400', '3. low': '432.9701', '4. close': '433.5900', '5. volume': '302481'}, '2023-06-16 14:00:00': {'1. open': '434.8100', '2. high': '434.8690', '3. low': '432.7800', '4. close': '433.0201', '5. volume': '531319'}, '2023-06-16 13:55:00': {'1. open': '434.8650', '2. high': '434.9900', '3. low': '434.1750', '4. close': '434.7200', '5. volume': '264976'}, '2023-06-16 13:50:00': {'1. open': '434.5000', '2. high': '434.9590', '3. low': '434.3568', '4. close': '434.8450', '5. volume': '244431'}, '2023-06-16 13:45:00': {'1. open': '435.6000', '2. high': '435.7000', '3. low': '434.2900', '4. close': '434.5400', '5. volume': '384553'}, '2023-06-16 13:40:00': {'1. open': '435.3800', '2. high': '435.7000', '3. low': '435.2400', '4. close': '435.6000', '5. volume': '231161'}, '2023-06-16 13:35:00': {'1. open': '434.9600', '2. high': '435.5300', '3. low': '434.8300', '4. close': '435.3700', '5. volume': '220860'}, '2023-06-16 13:30:00': {'1. open': '435.0801', '2. high': '435.7000', '3. low': '434.9001', '4. close': '435.0050', '5. volume': '269609'}, '2023-06-16 13:25:00': {'1. open': '435.5900', '2. high': '435.9500', '3. low': '434.7300', '4. close': '435.1050', '5. volume': '557125'}, '2023-06-16 13:20:00': {'1. open': '435.2900', '2. high': '435.9000', '3. low': '434.9700', '4. close': '435.6350', '5. volume': '340587'}, '2023-06-16 13:15:00': {'1. open': '435.4500', '2. high': '435.5000', '3. low': '434.7900', '4. close': '435.2800', '5. volume': '247660'}, '2023-06-16 13:10:00': {'1. open': '435.4471', '2. high': '435.6000', '3. low': '434.4500', '4. close': '435.4200', '5. volume': '319439'}, '2023-06-16 13:05:00': {'1. open': '435.5500', '2. high': '435.8500', '3. low': '434.9700', '4. close': '435.4400', '5. volume': '298346'}, '2023-06-16 13:00:00': {'1. open': '434.7000', '2. high': '435.9300', '3. low': '434.4401', '4. close': '435.5602', '5. volume': '366906'}, '2023-06-16 12:55:00': {'1. open': '435.1500', '2. high': '435.4400', '3. low': '434.3100', '4. close': '434.6800', '5. volume': '329862'}, '2023-06-16 12:50:00': {'1. open': '434.5950', '2. high': '435.5995', '3. low': '434.5300', '4. close': '435.2599', '5. volume': '419049'}, '2023-06-16 12:45:00': {'1. open': '434.3687', '2. high': '434.8100', '3. low': '434.1500', '4. close': '434.5700', '5. volume': '309784'}, '2023-06-16 12:40:00': {'1. open': '435.1350', '2. high': '435.1767', '3. low': '434.1401', '4. close': '434.2900', '5. volume': '402862'}, '2023-06-16 12:35:00': {'1. open': '436.2105', '2. high': '436.2800', '3. low': '434.8238', '4. close': '435.1899', '5. volume': '386082'}, '2023-06-16 12:30:00': {'1. open': '435.6000', '2. high': '436.3099', '3. low': '435.4400', '4. close': '436.2100', '5. volume': '345857'}, '2023-06-16 12:25:00': {'1. open': '435.9650', '2. high': '436.0900', '3. low': '435.2500', '4. close': '435.6801', '5. volume': '416344'}, '2023-06-16 12:20:00': {'1. open': '435.6436', '2. high': '435.9571', '3. low': '434.9130', '4. close': '435.9571', '5. volume': '477276'}, '2023-06-16 12:15:00': {'1. open': '435.8850', '2. high': '436.2599', '3. low': '435.3500', '4. close': '435.6434', '5. volume': '599251'}, '2023-06-16 12:10:00': {'1. open': '434.6100', '2. high': '437.2100', '3. low': '434.5401', '4. close': '435.9499', '5. volume': '1429035'}, '2023-06-16 12:05:00': {'1. open': '434.4300', '2. high': '434.7000', '3. low': '433.6232', '4. close': '434.6050', '5. volume': '443197'}, '2023-06-16 12:00:00': {'1. open': '434.3460', '2. high': '434.5100', '3. low': '433.6100', '4. close': '434.4599', '5. volume': '421151'}, '2023-06-16 11:55:00': {'1. open': '433.8000', '2. high': '434.3999', '3. low': '433.7300', '4. close': '434.3150', '5. volume': '497756'}, '2023-06-16 11:50:00': {'1. open': '432.7800', '2. high': '433.9900', '3. low': '432.3032', '4. close': '433.8500', '5. volume': '478587'}, '2023-06-16 11:45:00': {'1. open': '433.1965', '2. high': '434.0000', '3. low': '432.6000', '4. close': '432.8100', '5. volume': '419467'}, '2023-06-16 11:40:00': {'1. open': '432.0100', '2. high': '433.6800', '3. low': '431.9000', '4. close': '433.2200', '5. volume': '573642'}}

In [6]:
df = pd.DataFrame({
    'timestamp': ['2023-06-16 19:55:00', '2023-06-16 19:50:00', '2023-06-16 19:45:00', '2023-06-16 19:40:00', '2023-06-16 19:35:00'],
    'signal': ['BUY', 'SELL', 'BUY', 'SELL', 'BUY']
})

In [7]:
df

             timestamp signal
0  2023-06-16 19:55:00    BUY
1  2023-06-16 19:50:00   SELL
2  2023-06-16 19:45:00    BUY
3  2023-06-16 19:40:00   SELL
4  2023-06-16 19:35:00    BUY